# Generated by Django 5.0.6 on 2024-06-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
